module scs{
	module demos{
		module dynupdate
		{
			interface IDynamicUpdatable{
				string Backdoor (in string code);
				string BackdoorAsync (in string code);
				string GetBackdoorAsyncRet (in string key);
				string UpdateFacet (in string name, in string implementation);
				string UpdateFacetAsync (in string name, in string implementation);
				string GetUpdateFacetAsyncRet (in string key);
				string UpdateComponent(in ComponentId currentId,in ComponentId newId, in FacetDescriptions facets, in ReceptacleDescriptions receptacles);
				string UpdateComponentAsync(in ComponentId currentId,in ComponentId newId, in FacetDescriptions facets, in ReceptacleDescriptions receptacles);
				string GetUpdateComponentAsyncRet(in string key);
			};
		};
	};
};
